# =============================================================================
# _design/ingest_interface.py
# Interface contracts for ingest.py and the adapter pattern
# =============================================================================
# This file defines WHAT ingest.py and adapters/base.py must implement.
# It is NOT the implementation — Claude Code writes the implementations.
#
# RULES FOR CLAUDE CODE:
#   1. ingest.py is the ONLY entry point for adding documents to the system.
#      Nothing else should call adapters directly or call knowledge_store
#      without going through the ingest pipeline.
#   2. Adapters are discovered dynamically from sources.yaml — ingest.py
#      does NOT have a hardcoded list of adapters.
#   3. The pipeline order is fixed:
#      Adapter.fetch() → normalize() → Stage A → Stage B (per passage) →
#      triage() → knowledge_store.upsert_passage()
#   4. Multi-language: language is detected by the adapter (langdetect).
#      If language != "en", the document is still ingested but flagged.
#      Stage A and B prompts are sent in English regardless — GPT-4o handles
#      multilingual input. Do not translate before extraction.
#   5. All adapters must handle their own rate limiting. The base class
#      provides a rate_limit_wait() helper.
#   6. Adapter failures are logged and the document is marked
#      extraction_status="failed" in the index. Pipeline continues.
# =============================================================================

from abc import ABC, abstractmethod
from pathlib import Path
from typing import Optional, AsyncIterator
from schemas.document import Document


# =============================================================================
# ADAPTER BASE CLASS — all adapters inherit from this
# =============================================================================

class BaseAdapter(ABC):
    """
    Abstract base class for all source adapters.
    Subclasses: CorporatePDFAdapter, GoogleCSEAdapter, StructuredAPIAdapter,
                AcademicAdapter, PlaywrightScraperAdapter, RSSMonitorAdapter,
                ExaSearchAdapter
    """

    # Source type string — must match one of SOURCE_TYPES in schemas/document.py
    source_type: str = NotImplemented

    def __init__(self, config: dict):
        """
        config: dict loaded from the relevant entry in sources.yaml.
        Each adapter reads only the keys it needs.
        """
        self.config = config

    @abstractmethod
    async def fetch(self, query_or_path: str) -> AsyncIterator[Document]:
        """
        Main adapter method. Fetches content and yields Document objects.

        query_or_path can be:
          - A search query string (for CSE, Exa, academic adapters)
          - A URL (for scraper, RSS adapters)
          - A local file path (for corporate_pdf adapter)
          - An API query dict serialised as string (for structured API adapters)

        Must yield Document objects with all fields populated EXCEPT:
          - doc_id (generated by normalize())
          - content_hash (generated by normalize())
          - extraction_status (set to "pending" by normalize())

        Must handle:
          - Rate limiting (use self.rate_limit_wait())
          - Authentication errors (raise AdapterAuthError)
          - Network errors (retry 3x with exponential backoff, then raise AdapterFetchError)
          - Empty results (yield nothing, log a warning)
        """
        ...

    async def rate_limit_wait(self, requests_per_minute: int) -> None:
        """
        Base class provides this helper. Adapters call it before each API request.
        Implements token bucket rate limiting.
        requests_per_minute: from adapter's config entry in sources.yaml
        """
        ...


# =============================================================================
# ADAPTER-SPECIFIC EXCEPTIONS
# =============================================================================

class AdapterAuthError(Exception):
    """API key missing, expired, or invalid."""
    pass

class AdapterFetchError(Exception):
    """Network or API error after retries exhausted."""
    pass

class AdapterParseError(Exception):
    """Content could not be parsed into a Document."""
    pass


# =============================================================================
# INGEST PIPELINE INTERFACE — ingest.py must implement these
# =============================================================================

async def normalize(raw_doc: Document) -> Document:
    """
    Apply to every Document before any LLM processing.

    Must:
    1. Generate doc_id = UUID4
    2. Generate content_hash = SHA256(raw_text)
    3. Clean raw_text: remove null bytes, normalise whitespace, strip headers/footers
    4. Detect language using langdetect (override adapter's language field if differs)
    5. Truncate raw_text to 200,000 chars if longer (log a warning)
    6. Set extraction_status = "pending"
    7. Return the normalised Document

    Must NOT:
    - Summarise or modify the substance of raw_text
    - Call any LLM
    - Write to any index
    """
    ...


async def run_stage_a(doc: Document, prompt_path: Path) -> list[dict]:
    """
    Run Stage A extraction on a document.

    Loads prompt from prompt_path (e.g. prompts/collect_v1.txt).
    Substitutes template variables: {source_name}, {document_type},
    {reporting_year}, {language}, {company_name}, {document_text}.
    Calls GPT-4o-mini with the populated prompt.
    Parses the JSON array response.

    On JSON parse failure: retry once. If second attempt fails,
    return empty list and log the error.

    Returns: list of passage dicts (text, page_ref, topic_hint, etc.)
             as defined in prompts/collect_v1.txt output format
    """
    ...


async def run_stage_b(
    passage_dict: dict,
    doc: Document,
    taxonomy_excerpt: str,
    prompt_path: Path
) -> Optional[dict]:
    """
    Run Stage B classification on a single passage.

    Loads prompt from prompt_path (e.g. prompts/classify_v1.txt).
    Substitutes template variables: {source_name}, {document_type},
    {reporting_year}, {company_name}, {topic_hint}, {extraction_note},
    {passage_text}, {taxonomy_excerpt}.
    Calls GPT-4o-mini with the populated prompt.
    Parses the JSON object response.
    Validates all field values against controlled vocabularies in schemas/passage.py.

    On validation failure (invalid taxonomy value):
      - Set confidence = 0.0
      - Set classification_note = "invalid_taxonomy_value"
      - Still return the dict (do not discard the passage)

    On JSON parse failure: retry once.
    If second attempt fails: return None (passage will be discarded and logged).

    Returns: dict of Stage B fields, or None on unrecoverable failure.
    """
    ...


async def triage(passage: "ClassifiedPassage") -> "ClassifiedPassage":
    """
    Apply auto-approval/rejection rules and set review_priority.
    Called immediately after Stage B, before upsert_passage().

    Logic (in order — first matching rule wins):

    1. confidence < AUTO_REJECT_CONFIDENCE_THRESHOLD (0.40)
       → status = AUTO_REJECTED, priority = None

    2. ALL conditions true:
         confidence >= AUTO_APPROVE_CONFIDENCE_THRESHOLD (0.85)
         AND seed_category = True
         AND source_type in AUTO_APPROVE_SOURCE_TYPES
         AND "quantitative_claim" NOT in classification_note
         AND "qualifying_language_detected" NOT in classification_note
       → status = AUTO_APPROVED, priority = None

    3. Will be used in an imminent client-facing output (caller signals this
       by passing client_facing=True to ingest()):
       → status = PENDING_REVIEW, priority = P1_CLIENT

    4. "quantitative_claim" in classification_note OR extraction_note:
       → status = PENDING_REVIEW, priority = P2_QUANT

    5. seed_category = False:
       → status = PENDING_REVIEW, priority = P3_NEW_CAT

    6. Default:
       → status = PENDING_REVIEW, priority = P4_STANDARD

    Returns the passage with status and priority set.
    """
    ...


async def ingest(
    query_or_path: str,
    source_key: str,
    client_facing: bool = False
) -> dict:
    """
    Main entry point. Orchestrates the full pipeline for one source invocation.

    source_key: key in sources.yaml identifying the source and adapter to use.
    client_facing: if True, all passages from this run get P1_CLIENT priority.

    Pipeline:
    1. Load source config from sources.yaml using source_key
    2. Instantiate the correct adapter class
    3. adapter.fetch(query_or_path) → stream of raw Documents
    4. For each Document:
       a. normalize(doc)
       b. knowledge_store.deduplicate_document(content_hash) → skip if True
       c. knowledge_store.register_document(doc)
       d. run_stage_a(doc) → list of passage dicts
       e. For each passage dict:
          i.   get taxonomy_excerpt via taxonomy.get_taxonomy_excerpt_for_hint()
          ii.  run_stage_b(passage_dict, doc, taxonomy_excerpt) → stage_b_dict
          iii. build ClassifiedPassage from passage_dict + stage_b_dict + doc metadata
          iv.  triage(passage) → set status + priority
          v.   knowledge_store.upsert_passage(passage)
       f. knowledge_store.update_document_status(doc.doc_id, "extracted")

    Returns: summary dict {
      "documents_processed": int,
      "documents_skipped_duplicate": int,
      "passages_extracted": int,
      "passages_auto_approved": int,
      "passages_pending_review": int,
      "passages_auto_rejected": int,
      "errors": list[str]
    }
    """
    ...
